export const TEXT = {
  APP_NAME: "Easy Display Client",
  INTRO: "Host PC에서 Easy Display를 실행해주세요.",
  DISCOVERY_ERROR: "호스트 검색 중 오류 발생",
  DISCOVERY_NO_HOSTS: "발견된 호스트가 없습니다.",
  DISCOVERY_RETRY: "재시도",
  DISCOVERY_SEARCHING: "호스트를 찾는 중입니다...",
  HOST_BUTTON_TEXT: "호스트로 연결",
  HOST_IP_NOT_FOUND: "호스트 IP를 찾을 수 없습니다.",
  VIEW_GUIDE: "Easy Display\n가이드 보기",
  SETTING_BUTTON_LABEL: "설정",
  QUIT_BUTTON_LABEL: "종료",
  SLIDESHOW_NO_IMAGE: "이미지 파일이 없습니다.",
  SLIDESHOW_NO_VIDEO: "비디오 파일이 없습니다.",
  SLIDESHOW_NOT_SUPPORTED: "지원하지 않는 슬라이드 유형입니다.",
  SLIDESHOW_LOADING: "슬라이드 데이터를 가져오는중입니다.",
  SETTING_TITLE: "설정",
  SETTING_DESCRIPTION: "통신 설정을 변경할 수 있습니다.",
  SETTING_HOST_PORT: "HOST 통신 포트",
  SETTING_HOST_DISCOVERY_TIMEOUT: "HOST 탐색 시간(초)",
  SETTING_SLIDE_TRANSITION_SPEED: "슬라이드 화면전환 속도(밀리초)",
  SETTING_SAVE: "저장",
  SETTING_ALERT_TITLE: "설정 변경",
  SETTING_SAVE_SUCCESS: "설정이 저장되었습니다.",
  SETTING_EXIT_TITLE: "설정 변경",
  SETTING_EXIT_MESSAGE: "변경사항이 저장되지 않았습니다. 정말로 나가시겠습니까?",
  SETTING_EXIT_CANCEL: "취소",
  SETTING_EXIT_CONFIRM: "나가기",
  NOT_FOUND: "이 화면은 존재하지 않습니다.",
  NOT_FOUND_GO_HOME: "홈 화면으로 가기",
};
